import pandas as pd
from collections import Counter
import string

# Read the CSV file into a pandas DataFrame
file_path ="C:\\Users\\shake\\Desktop\\MSC- Data Science\\Thesis\\Tables\\Agancies Data-CrowdTangle\\CSA.csv"
data = pd.read_csv(file_path, dtype={'Message': str}, low_memory=False,encoding='latin-1')

# Function to count word frequency in a text
def count_words(text):
    # Remove punctuation and convert text to lowercase
    text = text.translate(str.maketrans('', '', string.punctuation)).lower().split()
    # Count word frequency
    word_count = Counter(text)
    return word_count

 # Define keywords for each field
international_relations_keywords = ['diplomacy', 'foreign policy', 'international cooperation', 'global affairs','Intent','Statement','Strategic Intent',
    'diplomat', 'ambassador', 'treaty', 'summit', 'embassy',
    'UN', 'United Nations', 'peacekeeping', 'world leaders', 'bilateral relations','agreement',' signing','Strategic Partnership','Prime Minister','ambassadors',
    'geopolitics', 'international organizations', 'security council', 'multilateral','international space agencies',
    'foreign minister', 'protocol', 'diplomatic mission', 'international dialogue',
    'conflict resolution', 'cross-cultural communication', 'trade agreements', 'global governance',
    'international treaties', 'diplomatic relations', 'international conferences', 'economic diplomacy',
    'cultural exchange', 'strategic alliances', 'peace negotiations', 'foreign affairs', 'policy analysis','Space Agency',
    'world affairs', 'coexistence', 'diplomatic corps', 'diplomatic immunity', 'geopolitical landscape',
    'foreign aid', 'regional cooperation', 'diplomatic ties', 'international summits', 'regional stability','Scientific and Technical Subcommittee','United Nations','Peaceful Uses of Outer Space','COPUOS','space resources',
    'diplomatic protocol', 'international politics', 'cross-border relations', 'international law',
    'diplomatic community', 'foreign trade', 'intergovernmental relations', 'public diplomacy',
    'global diplomacy', 'diplomatic negotiations', 'diplomatic missions', 'international conventions',
    'human rights diplomacy', 'foreign policy analysis', 'diplomatic strategies', 'diplomatic initiatives',
    'global cooperation', 'international affairs', 'peace agreements', 'intercultural communication',
    'global leadership', 'diplomatic efforts', 'foreign affairs analysis', 'diplomatic dialogue',
    'foreign relations', 'diplomatic ties', 'cross-border diplomacy', 'peacebuilding', 'diplomatic corps','ISS',
    'international collaboration', 'international communication', 'intergovernmental cooperation',
    'political dialogue', 'economic diplomacy', 'diplomatic relations', 'international security',
    'diplomatic engagement', 'international diplomacy', 'multilateral diplomacy', 'strategic partnerships','NASA',
    'diplomatic missions', 'diplomatic initiatives', 'cross-cultural diplomacy', 'global negotiations',
    'international agreements', 'diplomatic community', 'diplomatic protocol', 'intercultural relations',
    'diplomatic discourse', 'global governance', 'diplomatic dialogue', 'peace negotiations', 'geopolitical landscape',
    'foreign policy analysis', 'international treaties', 'diplomatic negotiations', 'world affairs',
    'coexistence', 'diplomatic efforts', 'international cooperation', 'economic diplomacy', 'cultural exchange',
    'regional stability', 'diplomatic ties', 'foreign aid', 'diplomatic missions', 'diplomatic immunity',
    'international summits', 'diplomatic strategies', 'foreign minister', 'protocol', 'international dialogue',
    'diplomatic ties', 'international law', 'human rights diplomacy', 'foreign trade', 'international politics',
    'cross-border relations', 'diplomatic protocol', 'international conventions', 'diplomatic community',
    'foreign policy analysis', 'global diplomacy', 'diplomatic negotiations', 'intergovernmental relations',
    'diplomatic relations', 'international collaboration', 'international communication', 'political dialogue',
    'diplomatic efforts', 'intercultural communication', 'foreign relations', 'international diplomacy',
    'international security', 'diplomatic engagement', 'diplomatic missions', 'cross-cultural diplomacy',
    'global negotiations', 'international agreements', 'diplomatic community', 'diplomatic protocol',
    'intercultural relations', 'diplomatic discourse', 'global governance', 'diplomatic dialogue',
    'peace negotiations', 'geopolitical landscape', 'foreign policy analysis', 'international treaties',
    'diplomatic negotiations', 'world affairs', 'coexistence', 'diplomatic efforts', 'international cooperation',
    'economic diplomacy', 'cultural exchange', 'regional stability', 'diplomatic ties', 'foreign aid',
    'diplomatic missions', 'diplomatic immunity', 'international summits', 'diplomatic strategies',
    'foreign minister', 'protocol', 'international dialogue', 'diplomatic ties', 'international law',
    'human rights diplomacy', 'foreign trade', 'international politics', 'cross-border relations',
    'diplomatic protocol', 'international conventions', 'diplomatic community', 'foreign policy analysis',
    'global diplomacy', 'diplomatic negotiations', 'intergovernmental relations', 'diplomatic relations',
    'international collaboration', 'international communication', 'political dialogue', 'diplomatic efforts',
    'intercultural communication', 'foreign relations', 'international diplomacy', 'international security',
    'diplomatic engagement', 'diplomatic missions', 'cross-cultural diplomacy', 'global negotiations',
    'international agreements', 'diplomatic community', 'diplomatic protocol', 'intercultural relations',
    'diplomatic discourse', 'global governance', 'diplomatic dialogue', 'peace negotiations', 'geopolitical landscape',
    'foreign policy analysis', 'international treaties', 'diplomatic negotiations', 'world affairs',
    'coexistence', 'diplomatic efforts', 'international cooperation', 'economic diplomacy', 'cultural exchange',
    'regional stability', 'diplomatic ties', 'foreign aid', 'diplomatic missions', 'diplomatic immunity',
    'international summits', 'diplomatic strategies', 'foreign minister', 'protocol', 'international dialogue',
    'diplomatic ties', 'international law', 'human rights diplomacy', 'foreign trade', 'international politics',
    'cross-border relations', 'diplomatic protocol', 'international conventions', 'diplomatic community',
    'foreign policy analysis', 'global diplomacy', 'diplomatic negotiations', 'intergovernmental relations',
    'diplomatic relations', 'international collaboration', 'international communication', 'political dialogue',
    'diplomatic efforts', 'intercultural communication', 'foreign relations', 'international diplomacy',
    'international security', 'diplomatic engagement', 'diplomatic missions', 'cross-cultural diplomacy',
    'global negotiations', 'international agreements', 'diplomatic community', 'diplomatic protocol',
    'intercultural relations', 'diplomatic discourse', 'global governance', 'diplomatic dialogue','Space Agency',
    'peace negotiations', 'geopolitical landscape', 'foreign policy analysis', 'international treaties',
    'diplomatic negotiations', 'world affairs', 'coexistence', 'diplomatic efforts', 'international cooperation',
    'economic diplomacy', 'cultural exchange', 'regional stability', 'diplomatic ties', 'foreign aid',
    'diplomatic missions', 'diplomatic immunity', 'international summits', 'diplomatic strategies',
    'foreign minister', 'protocol', 'international dialogue', 'diplomatic ties', 'international law',
    'human rights diplomacy', 'foreign trade', 'international politics', 'cross-border relations',
    'diplomatic protocol', 'international conventions', 'diplomatic community', 'foreign policy analysis',
    'global diplomacy', 'diplomatic negotiations', 'intergovernmental relations', 'diplomatic relations',
    'international collaboration', 'international communication', 'political dialogue', 'diplomatic efforts',
    'intercultural communication', 'foreign relations', 'international diplomacy', 'international security',
    'diplomatic engagement', 'diplomatic missions', 'cross-cultural diplomacy', 'global negotiations',
    'international agreements', 'diplomatic community', 'diplomatic protocol', 'intercultural relations',
    'diplomatic discourse', 'global governance', 'diplomatic dialogue', 'peace negotiations', 'geopolitical landscape',
    'foreign policy analysis', 'international treaties', 'diplomatic negotiations', 'world affairs',
    'coexistence', 'diplomatic efforts', 'international cooperation', 'economic diplomacy', 'cultural exchange',
    'regional stability', 'diplomatic ties', 'foreign aid', 'diplomatic missions', 'diplomatic immunity',
    'international summits', 'diplomatic strategies', 'foreign minister', 'protocol', 'international dialogue',
    'diplomatic ties', 'international law', 'human rights diplomacy', 'foreign trade', 'international politics',
    'cross-border relations', 'diplomatic protocol', 'international conventions', 'diplomatic community',
    'foreign policy analysis', 'global diplomacy', 'diplomatic negotiations', 'intergovernmental relations',
    'diplomatic relations', 'international collaboration', 'international communication', 'political dialogue',
    'diplomatic efforts', 'intercultural communication', 'foreign relations', 'international diplomacy',
    'international security', 'diplomatic engagement', 'diplomatic missions', 'cross-cultural diplomacy',
    'global negotiations', 'international agreements', 'diplomatic community', 'diplomatic protocol','announced',
    'intercultural relations', 'diplomatic discourse', 'global governance', 'diplomatic dialogue',
    'peace negotiations', 'geopolitical landscape', 'foreign policy analysis', 'international treaties',
    'diplomatic negotiations', 'world affairs', 'coexistence', 'diplomatic efforts', 'international cooperation',
    'economic diplomacy', 'cultural exchange', 'regional stability', 'diplomatic ties', 'foreign aid',
    'diplomatic missions', 'diplomatic immunity', 'international summits', 'diplomatic strategies',
    'foreign minister', 'protocol', 'international dialogue', 'diplomatic ties', 'international law',
    'human rights diplomacy', 'foreign trade', 'international politics', 'cross-border relations',
    'diplomatic protocol', 'international conventions', 'diplomatic community', 'foreign policy analysis',
    'global diplomacy', 'diplomatic negotiations', 'intergovernmental relations', 'diplomatic relations',
    'international collaboration', 'international communication', 'political dialogue', 'diplomatic efforts',
    'intercultural communication', 'foreign relations', 'international diplomacy', 'international security',
    'diplomatic engagement', 'diplomatic missions', 'cross-cultural diplomacy', 'global negotiations',
    'international agreements', 'diplomatic community', 'diplomatic protocol', 'intercultural relations',
    'diplomatic discourse', 'global governance', 'diplomatic dialogue', 'peace negotiations', 'geopolitical landscape',
    'foreign policy analysis', 'international treaties', 'diplomatic negotiations', 'world affairs',
    'coexistence', 'diplomatic efforts', 'international cooperation', 'economic diplomacy', 'cultural exchange',
    'regional stability', 'diplomatic ties', 'foreign aid', 'diplomatic missions', 'diplomatic immunity',
    'international summits', 'diplomatic strategies', 'foreign minister', 'protocol', 'international dialogue',
    'diplomatic ties', 'international law', 'human rights diplomacy', 'foreign trade', 'international politics','International Space Station',
    'cross-border relations', 'diplomatic protocol', 'international conventions', 'diplomatic community',
    'foreign policy analysis', 'global diplomacy', 'diplomatic negotiations', 'intergovernmental relations',
    'diplomatic relations', 'international collaboration', 'international communication', 'political dialogue',
    'diplomatic efforts', 'intercultural communication', 'foreign relations', 'international diplomacy',
    'international security', 'diplomatic engagement', 'diplomatic missions', 'cross-cultural diplomacy',
    'global negotiations', 'international agreements', 'diplomatic community', 'diplomatic protocol',
    'intercultural relations', 'diplomatic discourse', 'global governance', 'diplomatic dialogue',
    'peace negotiations', 'geopolitical landscape', 'foreign policy analysis', 'international treaties',
    'diplomatic negotiations', 'world affairs', 'coexistence', 'diplomatic efforts', 'international cooperation',
    'economic diplomacy', 'cultural exchange', 'regional stability', 'diplomatic ties', 'foreign aid',
    'diplomatic missions', 'diplomatic immunity', 'international summits', 'diplomatic strategies',
    'foreign minister', 'protocol', 'international dialogue', 'diplomatic ties', 'international law','Apollo 11 lunar mission','Apollo 11',
    'human rights diplomacy', 'foreign trade', 'international politics', 'cross-border relations',
    'diplomatic protocol', 'international conventions', 'diplomatic community', 'foreign policy analysis',
    'global diplomacy', 'diplomatic negotiations', 'intergovernmental relations', 'diplomatic relations',
    'international collaboration', 'international communication', 'political dialogue', 'diplomatic efforts',
    'intercultural communication', 'foreign relations', 'international diplomacy', 'international security',
    'diplomatic engagement', 'diplomatic missions', 'cross-cultural diplomacy', 'global negotiations',
    'international agreements', 'diplomatic community', 'diplomatic protocol', 'intercultural relations',
    'diplomatic discourse', 'global governance', 'diplomatic dialogue', 'peace negotiations', 'geopolitical landscape',
    'foreign policy analysis', 'international treaties', 'diplomatic negotiations', 'world affairs','International Space Station',
    'coexistence', 'diplomatic efforts', 'international cooperation', 'economic diplomacy', 'cultural exchange',
    'regional stability', 'diplomatic ties', 'foreign aid', 'diplomatic missions', 'diplomatic immunity',
    'international summits', 'diplomatic strategies', 'foreign minister', 'protocol', 'international dialogue',
    'diplomatic ties', 'international law', 'human rights diplomacy', 'foreign trade', 'international politics',
    'cross-border relations', 'diplomatic protocol', 'international conventions', 'diplomatic community','astronauts','International Space Station',
    'foreign policy analysis', 'global diplomacy', 'diplomatic negotiations', 'intergovernmental relations',
    'diplomatic relations', 'international collaboration', 'international communication', 'political dialogue','Happy New Year',
    'diplomatic efforts', 'intercultural communication', 'foreign relations', 'international diplomacy',
    'international security', 'diplomatic engagement', 'diplomatic missions', 'cross-cultural diplomacy','Artemis missions','global','space competitiveness'
    'global negotiations', 'international agreements', 'diplomatic community', 'diplomatic protocol',
    'intercultural relations', 'diplomatic discourse', 'global governance', 'diplomatic dialogue',' International Astronautical Congress',
    'peace negotiations', 'geopolitical landscape', 'foreign policy','James Webb Telescope','James Webb','Artemis','mission','highlights']

education_community_keywords =  ['education', 'community outreach', 'learning', 'social impact','Centre','webinar','student','projects','project','undergraduate','postgraduate',
    'school', 'students', 'teachers', 'classroom', 'education system','James Webb Telescope','James Webb','Artemis','Encourage','young', 'Register','Tag','LIVE NOW',
    'community development', 'volunteering', 'mentorship', 'youth engagement','Youth','Science','forum','STEM','Discovery','Prof.','Join us','NASA',
    'academic', 'scholarship', 'literacy', 'empowerment', 'skills development','educators','workshops','Join','Discovery Centre','Discovery','centre','Discover more',
    'educational program', 'student achievement', 'educational resources', 'school district','things you need to know about','deserts','Explore'
    'learning environment', 'education policy', 'curriculum development', 'educational technology','journey through our Universe',
    'STEM education', 'teacher training', 'inclusive education', 'special education','challenges','virtual tour','fly','International Space Station',
    'community building', 'civic engagement', 'social responsibility', 'philanthropy','newsletter','Discover','Happy New Year',
    'nonprofit organization', 'community service', 'charitable foundation', 'social justice','REGISTER NOW','REGISTER',
    'youth empowerment', 'education reform', 'educational outreach', 'educational equity','lunar eclipse','captured',
    'school leadership', 'parental involvement', 'learning community', 'after-school program','Did you know','highlights',
    'education empowerment', 'educational initiative', 'education advocacy', 'community impact','Environment Week','ESA',
    'educational achievement', 'community support', 'education for all', 'educational program','as seen from space','space robot',
    'community collaboration', 'school improvement', 'educational innovation', 'community building','mission',
    'youth development', 'education awareness', 'community education', 'educational opportunities',
    'education for sustainable development', 'education initiative', 'community development program','Artemis missions','Apollo 11 lunar mission','Apollo 11',
    'educational empowerment', 'community engagement', 'school partnership', 'educational outreach','meteor shower','meteors',
    'education enrichment', 'educational support', 'community involvement', 'education initiative','STEM',
    'community-based education', 'education access', 'education inclusion', 'community development initiative',
    'youth leadership', 'educational leadership', 'community enrichment', 'education for social change','Challenge',
    'school community', 'educational development', 'community education program', 'youth education program',' space exploration','space objects',
    'educational impact', 'community awareness', 'education transformation', 'community learning','stay up to date',
    'educational collaboration', 'inclusive community', 'education progress', 'community transformation',' experience ',
    'educational achievement', 'community empowerment', 'education engagement', 'youth outreach','journey through our Universe','ISS',
    'educational advancement', 'community initiative', 'education equality', 'community partnership','LIVE NOW','improves',
    'educational equality', 'community support program', 'education initiative', 'community enrichment','stories',
    'educational progress', 'community growth', 'education partnership', 'community education initiative','Reach for the','Watch LIVE','mars','moon','Apollo 11','learn more about',
    'educational transformation', 'community involvement program', 'education innovation', 'community development initiative',
    'educational development program', 'community building initiative', 'education outreach program', 'youth development program','satellites',
    'education initiative', 'community education partnership', 'educational transformation program', 'community support initiative','studying','intern',
    'education empowerment program', 'community development impact', 'educational outreach initiative', 'community awareness program','study','Venus',
    'education support program', 'community engagement initiative', 'educational impact program', 'community transformation initiative',
    'education initiative', 'community development collaboration', 'educational outreach collaboration', 'community learning initiative','Women and Girls in Science','engineer',
    'education partnership program', 'community support collaboration', 'educational transformation collaboration', 'community empowerment initiative',
    'education collaboration program', 'community development engagement', 'educational impact collaboration', 'community outreach initiative','Space and Sustainability',
    'education transformation program', 'community growth initiative', 'educational progress collaboration', 'community partnership program','Milky Way','astronauts',
    'education empowerment initiative', 'community enrichment collaboration', 'educational equality program', 'community support transformation','solar system',
    'education initiative', 'community development innovation', 'educational outreach innovation', 'community learning program',' take a tour','tour','climate events',
    'education partnership initiative', 'community support innovation','meteor shower', 'educational transformation innovation', 'community empowerment program','career',
    'education innovation program', 'community development impact initiative', 'educational outreach initiative', 'community awareness program','Space Week',
    'education support initiative', 'community engagement innovation', 'educational impact program', 'community transformation initiative','International Astronautical Congress',
    'education initiative', 'community development collaboration program','session','Register', 'educational outreach collaboration initiative', 'community learning initiative',
    'education partnership program', 'community support collaboration initiative', 'educational transformation collaboration program', 'community empowerment initiative',
    'education collaboration initiative program', 'community development engagement initiative', 'educational impact collaboration program', 'community outreach initiative program',
    'education transformation program initiative', 'community growth initiative program', 'educational progress collaboration initiative', 'community partnership program initiative',
    'education empowerment initiative program','Did you know','inspire','future space workforce', 'community enrichment collaboration initiative', 'educational equality program initiative', 'community support transformation initiative']

space_industry_keywords = [
    'satellite', 'astronomy','space sector','space industry','businesses','leaders','Space Edge computing','Edge computing','industry','companies','manufacturing',
    'rocket', 'cosmos', 'orbit', 'spacecraft', 'extraterrestrial','James Webb Telescope','James Webb','STEM','space industries',
    'celestial','planet','cosmonaut','space agency','workshops','new opportunities','investment opportunities','investment','investments','opportunities','national',
    'interstellar', 'telescope', 'space technology', 'astronaut', 'space station','space sector','launch applications','launch','applications',
    'galaxy', 'solar system', 'cosmic', 'exploration', 'stellar','sector', 'industry updates','regulatory activities','space industry','hiring',
    'interplanetary', 'space research', 'cosmic rays', 'astronomical', 'observatory','economy',
    'astrophysics', 'space travel', 'gravity', 'space science', 'astrobiology','challenges',
    'cosmic dust', 'stellar evolution', 'orbiting', 'space launch','Astrophotographer',
    'space shuttle', 'space innovation', 'extraterrestrial life', 'planetarium', 'spacewalk',
    'space probe', 'space phenomena', 'space weather', 'space agency', 'cosmic radiation',
    'space observation', 'rocket launch', 'space exploration',
    'space technology', 'satellite launch', 'space telescope', 'rocket science', 'space colonization','work','Food Production in Space',
    'space policy', 'space industry news', 'space research organization', 'space race', 'space-related',
    'orbital mechanics', 'space communication', 'space science research', 'space technology development', 'space mission updates','seen from space',
    'rocket propulsion', 'space travel innovation', 'celestial bodies', 'asteroid exploration',
    'cosmic phenomena', 'space discoveries', 'space agencies collaboration', 'planetary exploration', 'space station research','laser technology',
    'galactic exploration', 'astronomical discoveries', 'spacecraft development', 'space discoveries',
    'space industry advancements', 'international space cooperation', 'space exploration milestones', 'space exploration technology', 'space exploration missions',
    'rocket technology', 'space exploration breakthroughs', 'space research findings', 'space missions success', 'satellite technology', 
    'space research initiatives', 'space science discoveries', 'space exploration updates', 'astronaut achievements', 'space industry developments',
    'orbital missions', 'interplanetary exploration', 'space agency achievements','space debris','Job opportunity','to apply','apply',
    'space research collaborations', 'space technology innovations', 'satellite communication', 'space industry conferences', 'planetary science research',
    'space industry trends', 'space exploration history', 'cosmic exploration', 'space travel safety', 'space industry challenges',
    'rocket launch technologies', 'space science advancements', 'orbital mechanics research', 'space exploration documentary', 'space industry impact',
    'international space treaties', 'space exploration missions', 'space industry partnerships', 'rocket launch successes', 'space technology applications',
    'celestial bodies observation', 'astronomical breakthroughs', 'spacecraft technologies', 'space exploration documentaries', 'rocket launch advancements',
    'orbital mechanics innovations', 'space industry conferences', 'space research initiatives', 'space exploration achievements', 'space exploration goals',
    'satellite communication technologies', 'space industry collaborations', 'rocket propulsion innovations', 'space technology conferences', 'space exploration history',
    'cosmic exploration documentaries', 'space travel safety measures', 'space industry challenges and solutions', 'space industry impact on society',
    'rocket launch safety measures', 'space technology research', 'celestial bodies observation technologies','career','jobs','grow',
    'astronomical discoveries documentation', 'spacecraft technologies development', 'space exploration documentaries impact', 'rocket launch technologies advancements', 'space industry conferences outcomes',
    'space research initiatives outcomes', 'space exploration achievements impact', 'space exploration goals outcomes', 'satellite communication technologies impact', 'space industry collaborations outcomes',
    'rocket propulsion innovations outcomes', 'space technology conferences outcomes', 'space exploration history documentation', 'cosmic exploration documentaries impact', 'space travel safety measures outcomes',
    'space industry challenges and solutions outcomes', 'space industry impact on society outcomes', 'space exploration partnerships outcomes',
    'rocket launch safety measures outcomes', 'space technology research outcomes', 'celestial bodies observation technologies impact', 'astronomical discoveries documentation impact', 'spacecraft technologies development outcomes',
    'rocket launch technologies advancements impact', 'space industry conferences outcomes impact', 'space research initiatives outcomes impact', 'space exploration achievements impact on society',
    'satellite communication technologies impact on society', 'space industry collaborations outcomes impact', 'rocket propulsion innovations outcomes impact', 'space technology conferences outcomes impact',
    'cosmic exploration documentaries impact on society', 'space travel safety measures outcomes impact', 'space industry challenges and solutions outcomes impact', 'space exploration trends impact on society',
    'space industry impact on society outcomes impact', 'rocket launch safety measures outcomes impact', 'space technology research outcomes impact',
    'celestial bodies observation technologies impact on society', 'astronomical discoveries documentation impact on society', 'spacecraft technologies development outcomes impact', 'space exploration documentaries impact on society outcomes',
    'rocket launch technologies advancements impact on society', 'space industry conferences outcomes impact on society', 'space research initiatives outcomes impact on society', 'space exploration achievements impact on society outcomes','space law', 'international space law', 'Outer Space Treaty', 'space governance']
    

research_technology_keywords = [
    'Research Organisation', 'technology', 'innovation', 'scientific advancement','R&D', 'artificial intelligence', 'machine learning','edge processing','theories',
    'scientific research', 'lab', 'experiment', 'discovery', 'invention','Space Edge computing','Edge computing','Artemis','Dr','space debris',
    'researcher', 'scientist', 'breakthrough', 'data analysis', 'technological progress','global challenges','climate change', 'natural disasters', 'net zero',
    'cutting-edge', 'prototype', 'biotechnology', 'nanotechnology', 'engineering','James Webb Telescope','James Webb','Dr','Chief Scientist','Scientist',
    'research study', 'academic research', 'research methodology', 'research project', 'scientific community','mission','STEM','aurora',
    'research findings', 'research paper', 'research institute', 'research grant', 'research collaboration','solar system','Science','NASA',
    'research and development', 'innovative technology', 'emerging technology', 'technology trends', 'technology transfer','Mars','space systems',
    'technology adoption', 'technology integration', 'technological innovation', 'research innovation', 'scientific discovery','natural disasters',
    'scientific community', 'scientific literature', 'scientific journal', 'peer-reviewed', 'scientific conference','bushfires','flooding',
    'experimental research', 'applied research', 'fundamental research', 'scientific breakthrough', 'research publication','International Space Station',
    'research ethics', 'research funding', 'research outcomes', 'research impact', 'research outcomes', 'research quality','Artemis missions',
    'technology sector', 'technology solutions', 'cutting-edge technology', 'advanced technology', 'technology development','space robot',
    'technology assessment', 'innovation ecosystem', 'research infrastructure', 'research excellence', 'technology advancements',
    'research partnership', 'research collaboration', 'research network', 'technology standards', 'research initiative','far side of the Moon',
    'technology convergence', 'research center', 'technology-driven', 'research facilities', 'technology management','Earth','Rover',
    'research program', 'technology investment', 'innovation strategy', 'research ecosystem', 'technology market','deserts','Venus',
    'research focus', 'technology landscape', 'research hub', 'technology hub', 'research challenges', 'technology challenges','Food Production in Space',
    'research breakthroughs', 'technology impact', 'research and innovation', 'technology deployment', 'research and development',
    'technology solutions', 'research impact', 'technology trends', 'research integration', 'technology adoption','forecasting weather','climate events',
    'research frontier', 'technology frontier', 'research landscape', 'technology landscape', 'research agenda','sky','lunar eclipse',
    'technology agenda', 'research methodologies', 'technology transformation', 'research leadership', 'technology leadership','Researchers from University','Researchers','University',
    'research capabilities', 'technology capabilities', 'research collaboration', 'technology collaboration', 'research advancement',
    'technology advancement', 'research outcomes', 'technology outcomes', 'research excellence', 'technology excellence','meteor shower','meteors','data',
    'research strategy', 'technology strategy', 'research and technology', 'technology and innovation', 'research and development','alien life','alien',
    'technology and society', 'research and industry', 'technology and progress', 'research and innovation','Moon','deep space antenna','deep space',
    'technology and progress', 'research and technology trends', 'technology and future', 'research and development trends','Astrophotographer',
    'technology and innovation trends', 'research and technology impact', 'technology and societal impact', 'research and development impact','black hole','black holes',
    'technology and business', 'research and technology solutions', 'technology and global challenges', 'research and technology integration',
    'technology and economic growth', 'research and technology convergence', 'technology and sustainability', 'research and technology collaboration',
    'technology and research advancements', 'innovation and technology', 'research and technology advancements', 'technology and research excellence',
    'research and technology partnership', 'technology and research facilities', 'research and technology investment', 'technology and research capabilities',
    'research and technology deployment', 'technology and research agenda', 'research and technology leadership', 'technology and research transformation',
    'research and technology landscape', 'technology and research challenges', 'research and technology outcomes', 'technology and research strategy','satellites',
    'research and technology collaboration', 'technology and research advancement', 'research and technology outcomes', 'technology and research excellence',
    'research and technology strategy', 'technology and research capabilities','sun', 'research and technology solutions', 'technology and research impact',
    'research and technology integration', 'technology and research innovation', 'research and technology frontier', 'technology and research landscape','Read more',
    'research and technology transformation', 'technology and research methodologies', 'research and technology convergence', 'technology and research partnership',
    'research and technology deployment', 'technology and research infrastructure', 'research and technology collaboration', 'technology and research network',
    'research and technology center', 'technology and research program', 'research and technology facilities', 'technology and research focus','laser technology',
    'research and technology leadership', 'technology and research challenges', 'research and technology impact', 'technology and research agenda','Discover',
    'research and technology hub', 'technology and research market', 'research and technology deployment', 'technology and research challenges','space traffic management activities',
    'research and technology advancements', 'technology and research outcomes', 'research and technology solutions', 'technology and research ecosystem',
    'research and technology capabilities', 'technology and research convergence', 'research and technology landscape', 'technology and research excellence',
    'research and technology strategy', 'technology and research partnership', 'research and technology innovation', 'technology and research transformation',
    'research and technology leadership', 'technology and research advancements', 'research and technology investment', 'technology and research integration','robots',
    'research and technology deployment', 'technology and research agenda', 'research and technology outcomes', 'technology and research strategy',
    'research and technology collaboration', 'technology and research landscape', 'research and technology challenges', 'technology and research outcomes','Women and Girls in Science','engineer',
    'research and technology solutions', 'technology and research excellence', 'research and technology impact', 'technology and research integration',
    'research and technology convergence', 'technology and research deployment', 'research and technology partnership', 'technology and research facilities',
    'research and technology transformation', 'technology and research focus', 'research and technology leadership', 'technology and research agenda','Discover more',
    'research and technology hub', 'technology and research program', 'research and technology infrastructure', 'technology and research network','mars','water cycles','Earth Observation',
    'research and technology center', 'technology and research ecosystem', 'research and technology investment', 'technology and research capabilities',
    'research and technology deployment', 'technology and research convergence', 'research and technology landscape', 'technology and research excellence','planetary scientist',
    'Centre for Earth Observation','specialist','earth observation','Meteorology','weather','lunar eclipse','soil moisture','satellites','vegetation type','land use','Prof.','solar system']

# Create a dictionary mapping each category to its corresponding keywords
keywords_dict = {
    'International Relations': international_relations_keywords,
    'Education and Community': education_community_keywords,
    'Space Industry': space_industry_keywords,
    'Research and Technology': research_technology_keywords
}

# Create columns for each field
for field in keywords_dict.keys():
    data[f"{field}_Related"] = 0

# Function to classify posts based on the presence of keywords
def classify_posts(row, keywords_dict):
    # Check if the value in the 'Message' column is a string
    if isinstance(row['Message'], str):
        post = row['Message'].lower()  # Convert post text to lowercase
        word_count = count_words(post)

        # Set 1 for each field where there are related keywords
        for field in keywords_dict.keys():
            row[f"{field}_Related"] = int(any(keyword in word_count for keyword in keywords_dict[field]))
    return row

# Apply the updated classification function to categorize posts
data = data.apply(classify_posts, axis=1, keywords_dict=keywords_dict)

# Save the updated DataFrame to a new CSV file
output_file_path ="C:\\Users\\shake\\Desktop\\MSC- Data Science\\Thesis\\Tables\\Agancies Data-CrowdTangle\\CSA.csv"
data.to_csv(output_file_path, index=False)

print(data[['Message', 'International Relations_Related', 'Education and Community_Related', 'Space Industry_Related', 'Research and Technology_Related']])